name: Algolia Index
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: formium/algolia-docsearch-action@master
        with:
          algolia_application_id: "${{ secrets.ALGOLIA_APP_ID }}"
          algolia_api_key: "${{ secrets.ALGOLIA_API_KEY }}"
          file: "docs/algolia.json"
